/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class AdminDashboard extends javax.swing.JFrame {

    private JFrame frame;
    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        MoviePanel.setVisible(false);
        TicketPanel.setVisible(false);
        UserPanel.setVisible(false);
        RevenuePanel.setVisible(false);
        EditBtn.setVisible(false);
        DeleteBtn.setVisible(false);
        SearchBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        ExitBtn = new javax.swing.JButton();
        MovieManageBtn = new javax.swing.JButton();
        TicketManageBtn = new javax.swing.JButton();
        UserManageBtn = new javax.swing.JButton();
        RevenueBtn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        toppanel = new javax.swing.JPanel();
        TitleTxt = new javax.swing.JTextField();
        EditBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        SearchBtn = new javax.swing.JButton();
        RevenuePanel = new javax.swing.JScrollPane();
        MoviePanel = new javax.swing.JScrollPane();
        MovieTable = new javax.swing.JTable();
        TicketPanel = new javax.swing.JScrollPane();
        UserPanel = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(54, 33, 88));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitBtn.setBackground(new java.awt.Color(54, 33, 88));
        ExitBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/exit.png"))); // NOI18N
        ExitBtn.setText("     Exit");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });
        sidepanel.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 280, 60));

        MovieManageBtn.setBackground(new java.awt.Color(54, 33, 88));
        MovieManageBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MovieManageBtn.setForeground(new java.awt.Color(255, 255, 255));
        MovieManageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/movie-reel.png"))); // NOI18N
        MovieManageBtn.setText("     Movie manage");
        MovieManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovieManageBtnActionPerformed(evt);
            }
        });
        sidepanel.add(MovieManageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 280, 60));

        TicketManageBtn.setBackground(new java.awt.Color(54, 33, 88));
        TicketManageBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TicketManageBtn.setForeground(new java.awt.Color(255, 255, 255));
        TicketManageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/ticket.png"))); // NOI18N
        TicketManageBtn.setText("     Ticket manage");
        TicketManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketManageBtnActionPerformed(evt);
            }
        });
        sidepanel.add(TicketManageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 280, 60));

        UserManageBtn.setBackground(new java.awt.Color(54, 33, 88));
        UserManageBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UserManageBtn.setForeground(new java.awt.Color(255, 255, 255));
        UserManageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/people.png"))); // NOI18N
        UserManageBtn.setText("     User manage");
        UserManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserManageBtnActionPerformed(evt);
            }
        });
        sidepanel.add(UserManageBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 280, 60));

        RevenueBtn.setBackground(new java.awt.Color(54, 33, 88));
        RevenueBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RevenueBtn.setForeground(new java.awt.Color(255, 255, 255));
        RevenueBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/money.png"))); // NOI18N
        RevenueBtn.setText("     Revenue");
        RevenueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevenueBtnActionPerformed(evt);
            }
        });
        sidepanel.add(RevenueBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 280, 60));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(54, 33, 88));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Movie Ticket");
        jTextField1.setBorder(null);
        sidepanel.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        sidepanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 10));

        bg.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 570));

        toppanel.setBackground(new java.awt.Color(153, 0, 204));

        TitleTxt.setEditable(false);
        TitleTxt.setBackground(new java.awt.Color(153, 0, 204));
        TitleTxt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TitleTxt.setForeground(new java.awt.Color(255, 255, 255));
        TitleTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TitleTxt.setText("Adminstration Dashboard");
        TitleTxt.setBorder(null);

        EditBtn.setBackground(new java.awt.Color(153, 0, 204));
        EditBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EditBtn.setText("Edit");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setBackground(new java.awt.Color(153, 0, 204));
        DeleteBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        SearchBtn.setBackground(new java.awt.Color(153, 0, 204));
        SearchBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout toppanelLayout = new javax.swing.GroupLayout(toppanel);
        toppanel.setLayout(toppanelLayout);
        toppanelLayout.setHorizontalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanelLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(EditBtn)
                .addGap(55, 55, 55)
                .addComponent(DeleteBtn)
                .addGap(41, 41, 41)
                .addComponent(SearchBtn)
                .addGap(18, 18, 18))
            .addGroup(toppanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(TitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        toppanelLayout.setVerticalGroup(
            toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(toppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        bg.add(toppanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 530, -1));
        bg.add(RevenuePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MoviePanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                MoviePanelComponentHidden(evt);
            }
        });

        MovieTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Thumbnail", "Description", "Start time", "Room"
            }
        ));
        MoviePanel.setViewportView(MovieTable);

        bg.add(MoviePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 530, 400));
        bg.add(TicketPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 530, 400));

        UserPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fullname", "Email", "Phone", "Address", "Gender"
            }
        ));
        UserPanel.setViewportView(UserTable);

        bg.add(UserPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 530, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Comfirm if you want to exit", "Movie Ticket",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            dispose();
            new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void MovieManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieManageBtnActionPerformed
        // TODO add your handling code here:
        TitleTxt.setText("Movie Manage");
        MoviePanel.setVisible(true);
        TicketPanel.setVisible(false);
        UserPanel.setVisible(false);
        RevenuePanel.setVisible(false);
        EditBtn.setVisible(true);
        DeleteBtn.setVisible(true);
        SearchBtn.setVisible(true);
    }//GEN-LAST:event_MovieManageBtnActionPerformed

    private void TicketManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketManageBtnActionPerformed
        // TODO add your handling code here:
        TitleTxt.setText("Ticket Manage");
        TicketPanel.setVisible(true);
        MoviePanel.setVisible(false);
        UserPanel.setVisible(false);
        RevenuePanel.setVisible(false);
        EditBtn.setVisible(true);
        DeleteBtn.setVisible(true);
        SearchBtn.setVisible(true);
        
    }//GEN-LAST:event_TicketManageBtnActionPerformed

    private void UserManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserManageBtnActionPerformed
        // TODO add your handling code here:
        TitleTxt.setText("User Manage");
        UserPanel.setVisible(true);
        MoviePanel.setVisible(false);
        TicketPanel.setVisible(false);
        RevenuePanel.setVisible(false);
        EditBtn.setVisible(true);
        DeleteBtn.setVisible(true);
        SearchBtn.setVisible(true);
        
    }//GEN-LAST:event_UserManageBtnActionPerformed

    private void RevenueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevenueBtnActionPerformed
        // TODO add your handling code here:
        TitleTxt.setText("Revenue");
        RevenuePanel.setVisible(true);
        MoviePanel.setVisible(false);
        TicketPanel.setVisible(false);
        UserPanel.setVisible(false);
        EditBtn.setVisible(true);
        DeleteBtn.setVisible(true);
        SearchBtn.setVisible(true);
    }//GEN-LAST:event_RevenueBtnActionPerformed

    private void MoviePanelComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_MoviePanelComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_MoviePanelComponentHidden

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_EditBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton MovieManageBtn;
    private javax.swing.JScrollPane MoviePanel;
    private javax.swing.JTable MovieTable;
    private javax.swing.JButton RevenueBtn;
    private javax.swing.JScrollPane RevenuePanel;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JButton TicketManageBtn;
    private javax.swing.JScrollPane TicketPanel;
    private javax.swing.JTextField TitleTxt;
    private javax.swing.JButton UserManageBtn;
    private javax.swing.JScrollPane UserPanel;
    private javax.swing.JTable UserTable;
    private javax.swing.JPanel bg;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPanel toppanel;
    // End of variables declaration//GEN-END:variables
}
