/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

/**
 *
 * @author Admin
 */
public class AdminHome extends javax.swing.JFrame {

    private static int userId;
    /**
     * Creates new form AdminHome
     */
    public AdminHome(int userId) {
        initComponents();
        this.userId = userId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MovieManageBtn = new javax.swing.JButton();
        TicketManageBtn = new javax.swing.JButton();
        OrderBtn = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        UserManageBtn = new javax.swing.JButton();
        RevenueManageBtn = new javax.swing.JButton();
        EmployeeManageBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AdminHome");

        jPanel1.setBackground(new java.awt.Color(19, 15, 64));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        MovieManageBtn.setBackground(new java.awt.Color(48, 51, 107));
        MovieManageBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MovieManageBtn.setForeground(new java.awt.Color(255, 255, 255));
        MovieManageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/movie-reel (1).png"))); // NOI18N
        MovieManageBtn.setText("Movie Manage");
        MovieManageBtn.setToolTipText("");
        MovieManageBtn.setBorder(null);
        MovieManageBtn.setBorderPainted(false);
        MovieManageBtn.setFocusPainted(false);
        MovieManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovieManageBtnActionPerformed(evt);
            }
        });

        TicketManageBtn.setBackground(new java.awt.Color(48, 51, 107));
        TicketManageBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TicketManageBtn.setForeground(new java.awt.Color(255, 255, 255));
        TicketManageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/ticket-confirmation.png"))); // NOI18N
        TicketManageBtn.setText("Ticket Manage");
        TicketManageBtn.setBorder(null);
        TicketManageBtn.setBorderPainted(false);
        TicketManageBtn.setFocusPainted(false);
        TicketManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketManageBtnActionPerformed(evt);
            }
        });

        OrderBtn.setBackground(new java.awt.Color(48, 51, 107));
        OrderBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OrderBtn.setForeground(new java.awt.Color(255, 255, 255));
        OrderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/ticket1.png"))); // NOI18N
        OrderBtn.setText("Order Ticket");
        OrderBtn.setBorder(null);
        OrderBtn.setBorderPainted(false);
        OrderBtn.setFocusPainted(false);
        OrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderBtnActionPerformed(evt);
            }
        });

        LogOutBtn.setBackground(new java.awt.Color(48, 51, 107));
        LogOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogOutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/logout-variant.png"))); // NOI18N
        LogOutBtn.setText("Logout");
        LogOutBtn.setBorder(null);
        LogOutBtn.setBorderPainted(false);
        LogOutBtn.setFocusPainted(false);
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });

        UserManageBtn.setBackground(new java.awt.Color(48, 51, 107));
        UserManageBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UserManageBtn.setForeground(new java.awt.Color(255, 255, 255));
        UserManageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/account-circle-outline.png"))); // NOI18N
        UserManageBtn.setText("User Manage");
        UserManageBtn.setBorder(null);
        UserManageBtn.setBorderPainted(false);
        UserManageBtn.setFocusPainted(false);
        UserManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserManageBtnActionPerformed(evt);
            }
        });

        RevenueManageBtn.setBackground(new java.awt.Color(48, 51, 107));
        RevenueManageBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RevenueManageBtn.setForeground(new java.awt.Color(255, 255, 255));
        RevenueManageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/ticket-confirmation.png"))); // NOI18N
        RevenueManageBtn.setText("Revenue");
        RevenueManageBtn.setBorder(null);
        RevenueManageBtn.setBorderPainted(false);
        RevenueManageBtn.setFocusPainted(false);
        RevenueManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevenueManageBtnActionPerformed(evt);
            }
        });

        EmployeeManageBtn.setBackground(new java.awt.Color(48, 51, 107));
        EmployeeManageBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EmployeeManageBtn.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeManageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/account-circle-outline.png"))); // NOI18N
        EmployeeManageBtn.setText("Employee Manage");
        EmployeeManageBtn.setBorder(null);
        EmployeeManageBtn.setBorderPainted(false);
        EmployeeManageBtn.setFocusPainted(false);
        EmployeeManageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeManageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LogOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OrderBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmployeeManageBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MovieManageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(UserManageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TicketManageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                            .addComponent(RevenueManageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OrderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MovieManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TicketManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RevenueManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeeManageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(LogOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MovieManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieManageBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MovieManageBtnActionPerformed

    private void TicketManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketManageBtnActionPerformed
        // TODO add your handling code here:
        TicketManage ticketManage = new TicketManage(userId);
        ticketManage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_TicketManageBtnActionPerformed

    private void OrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderBtnActionPerformed
        // TODO add your handling code here:
        MovieOrder movieOrder = new MovieOrder(userId);
        this.setVisible(false);
    }//GEN-LAST:event_OrderBtnActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        // TODO add your handling code here:
        new LoginForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void UserManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserManageBtnActionPerformed
        // TODO add your handling code here:
        UserManage userManage = new UserManage(userId);
        userManage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_UserManageBtnActionPerformed

    private void RevenueManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevenueManageBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RevenueManageBtnActionPerformed

    private void EmployeeManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeManageBtnActionPerformed
        // TODO add your handling code here:
        EmployeeManage employeeManage = new EmployeeManage(userId);
        employeeManage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EmployeeManageBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome(userId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EmployeeManageBtn;
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JButton MovieManageBtn;
    private javax.swing.JButton OrderBtn;
    private javax.swing.JButton RevenueManageBtn;
    private javax.swing.JButton TicketManageBtn;
    private javax.swing.JButton UserManageBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
