/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author ngomi
 */
public class MovieTicket extends javax.swing.JFrame {

    /**
     * Creates new form MovieTicket
     */
    boolean a;
    public MovieTicket() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        maxMinClose = new javax.swing.JPanel();
        ButtonFullScreen = new javax.swing.JPanel();
        fullScreen = new javax.swing.JLabel();
        ButtonClose = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        menuIcon = new javax.swing.JPanel();
        ButtonMenu = new javax.swing.JPanel();
        btnMenu = new javax.swing.JLabel();
        ButtonSetting = new javax.swing.JPanel();
        btnSetting = new javax.swing.JLabel();
        menuHide = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(100, 50));

        Header.setBackground(new java.awt.Color(15, 19, 52));
        Header.setPreferredSize(new java.awt.Dimension(1266, 50));
        Header.setLayout(new java.awt.BorderLayout());

        maxMinClose.setBackground(new java.awt.Color(15, 19, 52));
        maxMinClose.setMinimumSize(new java.awt.Dimension(100, 50));
        maxMinClose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonFullScreen.setBackground(new java.awt.Color(15, 19, 52));
        ButtonFullScreen.setLayout(new java.awt.BorderLayout());

        fullScreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullScreen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/full_screen_32px.png"))); // NOI18N
        fullScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fullScreen.setPreferredSize(new java.awt.Dimension(50, 50));
        fullScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fullScreenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fullScreenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fullScreenMouseExited(evt);
            }
        });
        ButtonFullScreen.add(fullScreen, java.awt.BorderLayout.CENTER);

        maxMinClose.add(ButtonFullScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 50, 50));

        ButtonClose.setBackground(new java.awt.Color(15, 19, 52));
        ButtonClose.setLayout(new java.awt.BorderLayout());

        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/delete_32px.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        close.setPreferredSize(new java.awt.Dimension(50, 50));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        ButtonClose.add(close, java.awt.BorderLayout.CENTER);

        maxMinClose.add(ButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 50, 50));

        Header.add(maxMinClose, java.awt.BorderLayout.LINE_END);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        menu.setPreferredSize(new java.awt.Dimension(250, 587));
        menu.setLayout(new java.awt.BorderLayout());

        menuIcon.setBackground(new java.awt.Color(15, 19, 52));
        menuIcon.setPreferredSize(new java.awt.Dimension(50, 587));
        menuIcon.setLayout(new java.awt.BorderLayout());

        ButtonMenu.setBackground(new java.awt.Color(15, 19, 52));
        ButtonMenu.setPreferredSize(new java.awt.Dimension(50, 50));
        ButtonMenu.setLayout(new java.awt.BorderLayout());

        btnMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/back_32px.png"))); // NOI18N
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenuMouseExited(evt);
            }
        });
        ButtonMenu.add(btnMenu, java.awt.BorderLayout.CENTER);

        menuIcon.add(ButtonMenu, java.awt.BorderLayout.PAGE_START);

        ButtonSetting.setBackground(new java.awt.Color(15, 19, 52));
        ButtonSetting.setPreferredSize(new java.awt.Dimension(50, 50));
        ButtonSetting.setLayout(new java.awt.BorderLayout());

        btnSetting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/settings_32px.png"))); // NOI18N
        ButtonSetting.add(btnSetting, java.awt.BorderLayout.CENTER);

        menuIcon.add(ButtonSetting, java.awt.BorderLayout.PAGE_END);

        menu.add(menuIcon, java.awt.BorderLayout.LINE_START);

        menuHide.setBackground(new java.awt.Color(15, 19, 52));

        javax.swing.GroupLayout menuHideLayout = new javax.swing.GroupLayout(menuHide);
        menuHide.setLayout(menuHideLayout);
        menuHideLayout.setHorizontalGroup(
            menuHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        menuHideLayout.setVerticalGroup(
            menuHideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        menu.add(menuHide, java.awt.BorderLayout.CENTER);

        getContentPane().add(menu, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1086, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1336, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void changeColor(JPanel hover, Color rand) {
        hover.setBackground(rand);
    }
    public void hideShow(JPanel showHidePanel, boolean dashboard, JLabel button) {
        if(dashboard == true) {
            showHidePanel.setPreferredSize(new Dimension(50, showHidePanel.getHeight()));
            chageImage(button, "/logo//menu_32px.png");
        } else {
            showHidePanel.setPreferredSize(new Dimension(250, showHidePanel.getHeight()));
            chageImage(button, "/logo//back_32px.png");
        }
    }
    
    public void chageImage(JLabel button,  String imgString) {
        ImageIcon icon = new ImageIcon(getClass().getResource(imgString));
        button.setIcon(icon);
    }
    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
        changeColor(ButtonClose, new Color(25,29,74));
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
        changeColor(ButtonClose, new Color(5,10,46));
    }//GEN-LAST:event_closeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void fullScreenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullScreenMouseEntered
        // TODO add your handling code here:
        changeColor(ButtonFullScreen, new Color(25,29,74));
    }//GEN-LAST:event_fullScreenMouseEntered

    private void fullScreenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullScreenMouseExited
        // TODO add your handling code here:
        changeColor(ButtonFullScreen, new Color(5,10,46));
    }//GEN-LAST:event_fullScreenMouseExited

    private void fullScreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fullScreenMouseClicked
        // TODO add your handling code here:
        if(this.getExtendedState()!= MovieTicket.MAXIMIZED_BOTH) {
            this.setExtendedState(MovieTicket.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(MovieTicket.NORMAL);
        }
    }//GEN-LAST:event_fullScreenMouseClicked

    private void btnMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseEntered
        // TODO add your handling code here:
        changeColor(ButtonMenu, new Color(25,29,74));
    }//GEN-LAST:event_btnMenuMouseEntered

    private void btnMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseExited
        // TODO add your handling code here:
        changeColor(ButtonMenu, new Color(5,10,46));
    }//GEN-LAST:event_btnMenuMouseExited

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
        // TODO add your handling code here:
        if(a == true ){
            hideShow(menu, a, btnMenu);
            SwingUtilities.updateComponentTreeUI(this);
            a = false;
        } else {
            hideShow(menu, a,btnMenu);
            SwingUtilities.updateComponentTreeUI(this);           
            a = true;
        }
    }//GEN-LAST:event_btnMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovieTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonClose;
    private javax.swing.JPanel ButtonFullScreen;
    private javax.swing.JPanel ButtonMenu;
    private javax.swing.JPanel ButtonSetting;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel btnMenu;
    private javax.swing.JLabel btnSetting;
    private javax.swing.JLabel close;
    private javax.swing.JLabel fullScreen;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel maxMinClose;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuHide;
    private javax.swing.JPanel menuIcon;
    // End of variables declaration//GEN-END:variables
}
