/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import DAO.UserDAO;
import Model.User;
import java.awt.Color;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author ngomi
 */
public class RegisterForm extends javax.swing.JFrame {

    private JFrame frame;
    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fullNameTxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        genderBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        confirmPasswordTxt = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        regiseterBtn = new javax.swing.JButton();
        check = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        loginForm = new javax.swing.JLabel();
        closetBtn = new javax.swing.JPanel();
        ExitBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/video-vintage.png"))); // NOI18N
        jLabel2.setText("Register");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 210, 60));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Full Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 40));

        fullNameTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        fullNameTxt.setForeground(new java.awt.Color(102, 102, 102));
        fullNameTxt.setText("Enter Full Name");
        fullNameTxt.setBorder(null);
        fullNameTxt.setOpaque(false);
        fullNameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fullNameTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fullNameTxtFocusLost(evt);
            }
        });
        fullNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullNameTxtActionPerformed(evt);
            }
        });
        jPanel2.add(fullNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 490, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 490, -1));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setText("Email:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 30));

        emailTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        emailTxt.setForeground(new java.awt.Color(102, 102, 102));
        emailTxt.setText("Enter Email");
        emailTxt.setBorder(null);
        emailTxt.setOpaque(false);
        emailTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTxtFocusLost(evt);
            }
        });
        jPanel2.add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 240, 40));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 240, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setText("Address:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, 40));

        addressTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        addressTxt.setForeground(new java.awt.Color(102, 102, 102));
        addressTxt.setText("Enter Address");
        addressTxt.setBorder(null);
        addressTxt.setOpaque(false);
        addressTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressTxtFocusLost(evt);
            }
        });
        jPanel2.add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 490, 40));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 490, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setText("Phone:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 70, 30));

        phoneTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        phoneTxt.setForeground(new java.awt.Color(102, 102, 102));
        phoneTxt.setText("Enter Phone Number");
        phoneTxt.setBorder(null);
        phoneTxt.setOpaque(false);
        phoneTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneTxtFocusLost(evt);
            }
        });
        jPanel2.add(phoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 240, 40));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 240, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setText("Gender:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 70, 30));

        genderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Male", "Female", "Other" }));
        genderBox.setOpaque(false);
        jPanel2.add(genderBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 90, 30));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel8.setText("Password:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 90, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel9.setText("Confirm Password:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 140, -1));

        passwordTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        passwordTxt.setForeground(new java.awt.Color(102, 102, 102));
        passwordTxt.setText("Password");
        passwordTxt.setBorder(null);
        passwordTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTxtFocusLost(evt);
            }
        });
        jPanel2.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 240, 40));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 240, -1));

        confirmPasswordTxt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        confirmPasswordTxt.setForeground(new java.awt.Color(102, 102, 102));
        confirmPasswordTxt.setText("Password");
        confirmPasswordTxt.setBorder(null);
        confirmPasswordTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                confirmPasswordTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                confirmPasswordTxtFocusLost(evt);
            }
        });
        confirmPasswordTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                confirmPasswordTxtMouseEntered(evt);
            }
        });
        jPanel2.add(confirmPasswordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 240, 40));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 240, 10));

        regiseterBtn.setBackground(new java.awt.Color(255, 255, 255));
        regiseterBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        regiseterBtn.setText("Register");
        regiseterBtn.setBorder(new javax.swing.border.MatteBorder(null));
        regiseterBtn.setBorderPainted(false);
        regiseterBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regiseterBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                regiseterBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                regiseterBtnMouseExited(evt);
            }
        });
        regiseterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regiseterBtnActionPerformed(evt);
            }
        });
        jPanel2.add(regiseterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 160, 40));

        check.setBackground(new java.awt.Color(255, 255, 255));
        check.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        jPanel2.add(check, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 20, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Terms & Conditions");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 110, 20));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Agree");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 40, 20));

        loginForm.setBackground(new java.awt.Color(255, 255, 255));
        loginForm.setFont(new java.awt.Font("Tahoma", 3, 16)); // NOI18N
        loginForm.setForeground(new java.awt.Color(0, 153, 0));
        loginForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginForm.setText("Already have an account?");
        loginForm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginForm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginFormMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginFormMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginFormMouseExited(evt);
            }
        });
        jPanel2.add(loginForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 220, 20));

        closetBtn.setBackground(new java.awt.Color(255, 255, 255));
        closetBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/close.png"))); // NOI18N
        ExitBtn.setPreferredSize(new java.awt.Dimension(50, 50));
        ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBtnMouseExited(evt);
            }
        });
        closetBtn.add(ExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.add(closetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 50, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 590));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 590));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 590));

        setSize(new java.awt.Dimension(560, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fullNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameTxtActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkActionPerformed

    private void loginFormMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFormMouseEntered
        // TODO add your handling code here:
        Border label_border = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(0,153,0));
        loginForm.setBorder(label_border);
    }//GEN-LAST:event_loginFormMouseEntered

    private void loginFormMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFormMouseExited
        // TODO add your handling code here:
        loginForm.setBorder(null);
    }//GEN-LAST:event_loginFormMouseExited

    private void loginFormMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginFormMouseClicked
        // TODO add your handling code here:
        dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_loginFormMouseClicked

    private void ExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseClicked
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Comfirm if you want to exit", "Movie Ticket",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitBtnMouseClicked

    private void ExitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseEntered
        // TODO add your handling code here:
        changeColor(closetBtn, Color.red);
    }//GEN-LAST:event_ExitBtnMouseEntered

    private void ExitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseExited
        // TODO add your handling code here:
        changeColor(closetBtn, Color.WHITE);
    }//GEN-LAST:event_ExitBtnMouseExited

    private void fullNameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fullNameTxtFocusGained
        // TODO add your handling code here:
        fullNameTxt.setText("");
    }//GEN-LAST:event_fullNameTxtFocusGained

    private void fullNameTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fullNameTxtFocusLost
        // TODO add your handling code here:
        if(fullNameTxt.getText().equals("")) {
            
            fullNameTxt.setForeground(new Color(204,204,204));
        } else {
            fullNameTxt.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_fullNameTxtFocusLost

    private void emailTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTxtFocusGained
        // TODO add your handling code here:
        emailTxt.setText("");
    }//GEN-LAST:event_emailTxtFocusGained

    private void emailTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTxtFocusLost
        // TODO add your handling code here:
        if(emailTxt.getText().equals("")) {
            emailTxt.setForeground(new Color(204,204,204));
        } else {
            emailTxt.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_emailTxtFocusLost

    private void phoneTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneTxtFocusGained
        // TODO add your handling code here:
        phoneTxt.setText("");
    }//GEN-LAST:event_phoneTxtFocusGained

    private void phoneTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneTxtFocusLost
        // TODO add your handling code here:
        if(phoneTxt.getText().equals("")) {
            phoneTxt.setText("Enter Phone Number");
            phoneTxt.setForeground(new Color(204,204,204));
        } else {
            phoneTxt.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_phoneTxtFocusLost

    private void addressTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressTxtFocusGained
        // TODO add your handling code here:
        addressTxt.setText("");
    }//GEN-LAST:event_addressTxtFocusGained

    private void addressTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressTxtFocusLost
        // TODO add your handling code here:
        if(addressTxt.getText().equals("")) {
            addressTxt.setText("Enter Address");
            addressTxt.setForeground(new Color(204,204,204));
        } else {
            addressTxt.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_addressTxtFocusLost

    private void passwordTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusGained
        // TODO add your handling code here:
        passwordTxt.setText("");
    }//GEN-LAST:event_passwordTxtFocusGained

    private void passwordTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTxtFocusLost
        // TODO add your handling code here:
        if(new String(passwordTxt.getPassword()).equals("")) {
            passwordTxt.setText("Password");
            passwordTxt.setForeground(new Color(204,204,204));
        } else {
            passwordTxt.setForeground(Color.BLACK);
        }
                
    }//GEN-LAST:event_passwordTxtFocusLost

    private void confirmPasswordTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPasswordTxtFocusGained
        // TODO add your handling code here:
        confirmPasswordTxt.setText("");
    }//GEN-LAST:event_confirmPasswordTxtFocusGained

    private void regiseterBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regiseterBtnMouseEntered
        // TODO add your handling code here:
        regiseterBtn.setBackground(Color.BLACK);
        regiseterBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_regiseterBtnMouseEntered

    private void regiseterBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regiseterBtnMouseExited
        // TODO add your handling code here:
        regiseterBtn.setBackground(Color.WHITE);
        regiseterBtn.setForeground(Color.BLACK);
    }//GEN-LAST:event_regiseterBtnMouseExited

    private void confirmPasswordTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmPasswordTxtMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmPasswordTxtMouseEntered

    private void confirmPasswordTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPasswordTxtFocusLost
        // TODO add your handling code here:
        if(new String(confirmPasswordTxt.getPassword()).equals("")) {
            confirmPasswordTxt.setText("Password");
            confirmPasswordTxt.setForeground(new Color(204,204,204));
        } else {
            confirmPasswordTxt.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_confirmPasswordTxtFocusLost

    private void regiseterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regiseterBtnActionPerformed
        // TODO add your handling code here:
        String fullName = fullNameTxt.getText();
        String email = emailTxt.getText();
        String phone = phoneTxt.getText();
        String gender = genderBox.getSelectedItem().toString();
        String address = addressTxt.getText();
        String password = new String(passwordTxt.getPassword());
        String confirmPassword = new String(confirmPasswordTxt.getPassword());
        StringBuilder sb = new StringBuilder();
        java.util.Date dateCreateDateAccount = new java.util.Date();
        java.util.Date dateUpdatDateAccount = new java.util.Date();
        if(fullName.equals("")) {
            sb.append("Full name is empty\n");
        }
        Pattern emailPattern = Pattern.compile("^[\\w!#$%&’*+/=?`{|}~^-]+(?:\\.[\\w!#$%&’*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$");
        Matcher emailMatcher = emailPattern.matcher(emailTxt.getText());
        if(email.equals("")) {
            sb.append("Email is empty \n");
        } else if(!emailMatcher.find()) {
            sb.append("Email must be abc@gmail.com \n");
        }
        Pattern phonePattern = Pattern.compile("[0-9]{10}");
        Matcher phoneMatcher = phonePattern.matcher(phone);
        if(phone.equals("")) {
            sb.append("phone is empty \n");
        } else if(!phoneMatcher.find()) {
            sb.append("Phone must be 0-9 at least 10 \n");
        }
        if(gender.equals("Choose")) {
            sb.append("Gender is empty\n");
        }
        Pattern passwordPattern = Pattern.compile("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=\\S+$).{8,}$");
        Matcher passwordMatcher = passwordPattern.matcher(password);
        if(password.equals("")) {
            sb.append("password is empty \n");
        } else if(!passwordMatcher.find()) {
            sb.append("Password must be at least once a digit, a lower case, an upper case, no whitespace,  at least eight character\n");
        }
        if(!confirmPassword.equals(password)) {
            sb.append("Confirm Password dose not match\n");
        }
        if(address.equals("")) {
            sb.append("Address is empty\n");
        }
        
        if(!check.isSelected()) {
            sb.append("You must agree terms and conditions\n");
        }
        if(sb.length()>0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            User user = new User(fullName,email,phone,password,3,gender,dateCreateDateAccount,dateUpdatDateAccount,address);
            UserDAO.Insert(user);
            dispose();
            new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_regiseterBtnActionPerformed
    
    public void changeColor(JPanel hover, Color rand) {
        hover.setBackground(rand);
        if(addressTxt.getText().equals("")) {
            addressTxt.setText("Enter Phone Number");
            addressTxt.setForeground(new Color(204,204,204));
        } else {
            addressTxt.setForeground(Color.BLACK);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExitBtn;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JCheckBox check;
    private javax.swing.JPanel closetBtn;
    private javax.swing.JPasswordField confirmPasswordTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField fullNameTxt;
    private javax.swing.JComboBox<String> genderBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel loginForm;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JButton regiseterBtn;
    // End of variables declaration//GEN-END:variables
}
