/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class TicketManage extends javax.swing.JFrame {

    private JFrame frame;
    /**
     * Creates new form MovieDetail
     */
    public TicketManage() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg2 = new javax.swing.JPanel();
        sidepanel2 = new javax.swing.JPanel();
        ExitBtn2 = new javax.swing.JButton();
        MovieManageBtn2 = new javax.swing.JButton();
        TicketManageBtn2 = new javax.swing.JButton();
        UserManageBtn2 = new javax.swing.JButton();
        RevenueBtn2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        toppanel2 = new javax.swing.JPanel();
        TitleTxt2 = new javax.swing.JTextField();
        EditBtn2 = new javax.swing.JButton();
        DeleteBtn2 = new javax.swing.JButton();
        SearchBtn2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bg2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel2.setBackground(new java.awt.Color(54, 33, 88));
        sidepanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ExitBtn2.setBackground(new java.awt.Color(54, 33, 88));
        ExitBtn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ExitBtn2.setForeground(new java.awt.Color(255, 255, 255));
        ExitBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/exit.png"))); // NOI18N
        ExitBtn2.setText("     Exit");
        ExitBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtn2ExitBtnActionPerformed(evt);
            }
        });
        sidepanel2.add(ExitBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 280, 60));

        MovieManageBtn2.setBackground(new java.awt.Color(54, 33, 88));
        MovieManageBtn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        MovieManageBtn2.setForeground(new java.awt.Color(255, 255, 255));
        MovieManageBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/movie-reel.png"))); // NOI18N
        MovieManageBtn2.setText("     Movie manage");
        MovieManageBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MovieManageBtn2MovieManageBtnActionPerformed(evt);
            }
        });
        sidepanel2.add(MovieManageBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 280, 60));

        TicketManageBtn2.setBackground(new java.awt.Color(54, 33, 88));
        TicketManageBtn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TicketManageBtn2.setForeground(new java.awt.Color(255, 255, 255));
        TicketManageBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/ticket.png"))); // NOI18N
        TicketManageBtn2.setText("     Ticket manage");
        TicketManageBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TicketManageBtn2TicketManageBtnActionPerformed(evt);
            }
        });
        sidepanel2.add(TicketManageBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 280, 60));

        UserManageBtn2.setBackground(new java.awt.Color(54, 33, 88));
        UserManageBtn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        UserManageBtn2.setForeground(new java.awt.Color(255, 255, 255));
        UserManageBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/people.png"))); // NOI18N
        UserManageBtn2.setText("     User manage");
        UserManageBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserManageBtn2UserManageBtnActionPerformed(evt);
            }
        });
        sidepanel2.add(UserManageBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 280, 60));

        RevenueBtn2.setBackground(new java.awt.Color(54, 33, 88));
        RevenueBtn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RevenueBtn2.setForeground(new java.awt.Color(255, 255, 255));
        RevenueBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/money.png"))); // NOI18N
        RevenueBtn2.setText("     Revenue");
        RevenueBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevenueBtn2RevenueBtnActionPerformed(evt);
            }
        });
        sidepanel2.add(RevenueBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 280, 60));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(54, 33, 88));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Movie Ticket");
        jTextField3.setBorder(null);
        sidepanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        sidepanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 250, 10));

        bg2.add(sidepanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 840));

        toppanel2.setBackground(new java.awt.Color(153, 0, 204));

        TitleTxt2.setEditable(false);
        TitleTxt2.setBackground(new java.awt.Color(153, 0, 204));
        TitleTxt2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TitleTxt2.setForeground(new java.awt.Color(255, 255, 255));
        TitleTxt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TitleTxt2.setText("Ticket Manage");
        TitleTxt2.setBorder(null);

        EditBtn2.setBackground(new java.awt.Color(153, 0, 204));
        EditBtn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        EditBtn2.setText("Edit");
        EditBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtn2EditBtnActionPerformed(evt);
            }
        });

        DeleteBtn2.setBackground(new java.awt.Color(153, 0, 204));
        DeleteBtn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        DeleteBtn2.setText("Delete");
        DeleteBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtn2DeleteBtnActionPerformed(evt);
            }
        });

        SearchBtn2.setBackground(new java.awt.Color(153, 0, 204));
        SearchBtn2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SearchBtn2.setText("Search");
        SearchBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtn2SearchBtnActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(153, 0, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Add");

        javax.swing.GroupLayout toppanel2Layout = new javax.swing.GroupLayout(toppanel2);
        toppanel2.setLayout(toppanel2Layout);
        toppanel2Layout.setHorizontalGroup(
            toppanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanel2Layout.createSequentialGroup()
                .addGroup(toppanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(toppanel2Layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(TitleTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(toppanel2Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jButton3)
                        .addGap(124, 124, 124)
                        .addComponent(EditBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123)
                        .addComponent(DeleteBtn2)
                        .addGap(165, 165, 165)
                        .addComponent(SearchBtn2)))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        toppanel2Layout.setVerticalGroup(
            toppanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toppanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(TitleTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 621, Short.MAX_VALUE)
                .addGroup(toppanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                    .addComponent(EditBtn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SearchBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        bg2.add(toppanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 1150, 760));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg2, javax.swing.GroupLayout.PREFERRED_SIZE, 728, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtn2ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtn2ExitBtnActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Comfirm if you want to exit", "Movie Ticket",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
        dispose();
        new LoginForm().setVisible(true);
        }
    }//GEN-LAST:event_ExitBtn2ExitBtnActionPerformed

    private void MovieManageBtn2MovieManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MovieManageBtn2MovieManageBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new MovieManage().setVisible(true);
    }//GEN-LAST:event_MovieManageBtn2MovieManageBtnActionPerformed

    private void TicketManageBtn2TicketManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TicketManageBtn2TicketManageBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new TicketManage().setVisible(true);
    }//GEN-LAST:event_TicketManageBtn2TicketManageBtnActionPerformed

    private void UserManageBtn2UserManageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserManageBtn2UserManageBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new UserManage().setVisible(true);
    }//GEN-LAST:event_UserManageBtn2UserManageBtnActionPerformed

    private void RevenueBtn2RevenueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevenueBtn2RevenueBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        new RevenueManage().setVisible(true);
    }//GEN-LAST:event_RevenueBtn2RevenueBtnActionPerformed

    private void EditBtn2EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtn2EditBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditBtn2EditBtnActionPerformed

    private void DeleteBtn2DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtn2DeleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBtn2DeleteBtnActionPerformed

    private void SearchBtn2SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtn2SearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBtn2SearchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBtn2;
    private javax.swing.JButton EditBtn2;
    private javax.swing.JButton ExitBtn2;
    private javax.swing.JButton MovieManageBtn2;
    private javax.swing.JButton RevenueBtn2;
    private javax.swing.JButton SearchBtn2;
    private javax.swing.JButton TicketManageBtn2;
    private javax.swing.JTextField TitleTxt2;
    private javax.swing.JButton UserManageBtn2;
    private javax.swing.JPanel bg2;
    private javax.swing.JButton jButton3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel sidepanel2;
    private javax.swing.JPanel toppanel2;
    // End of variables declaration//GEN-END:variables
}
